### ISSUE TITLE
Cannot enter folder containing filenames with umlauts

### ISSUE THREAD

**Issue by sm8ps** [flathub/de.lernsoftware_filius.Filius#1]
Apparently the Flatpak version does not handle Unicode characters.
```
Exception in thread "Basic L&F File Loading Thread" java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/stefan/??ffentlich
	at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
	at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at java.desktop/sun.awt.shell.ShellFolder.getShellFolder(ShellFolder.java:247)
	at java.desktop/javax.swing.filechooser.FileSystemView.getFiles(FileSystemView.java:523)
	at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run0(BasicDirectoryModel.java:300)
	at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run(BasicDirectoryModel.java:289)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mikebarkmin** [comment]
For me, it works for version 2.5.1.

**Comment by sm8ps** [comment]
I can confirm that the problem does not arise with version 2.5.1. Closing this issue.
